// Generated by scripts/generate-catalog.mjs. Do not edit manually.
window.GAME_CATALOG = [
  {
    "name": "exam語音報讀程式正確步驟一",
    "url": "./exam%E8%AA%9E%E9%9F%B3%E5%A0%B1%E8%AE%80%E7%A8%8B%E5%BC%8F%E6%AD%A3%E7%A2%BA%E6%AD%A5%E9%A9%9F%E4%B8%80.html",
    "imgUrl": "./exam%E8%AA%9E%E9%9F%B3%E5%A0%B1%E8%AE%80%E7%A8%8B%E5%BC%8F%E6%AD%A3%E7%A2%BA%E6%AD%A5%E9%A9%9F%E4%B8%80.jpg"
  },
  {
    "name": "exam語音報讀程式步驟二",
    "url": "./exam%E8%AA%9E%E9%9F%B3%E5%A0%B1%E8%AE%80%E7%A8%8B%E5%BC%8F%E6%AD%A5%E9%A9%9F%E4%BA%8C.html",
    "imgUrl": "./exam%E8%AA%9E%E9%9F%B3%E5%A0%B1%E8%AE%80%E7%A8%8B%E5%BC%8F%E6%AD%A5%E9%A9%9F%E4%BA%8C.jpg"
  },
  {
    "name": "vote",
    "url": "./vote.html",
    "imgUrl": null
  },
  {
    "name": "人臉替換程式",
    "url": "./%E4%BA%BA%E8%87%89%E6%9B%BF%E6%8F%9B%E7%A8%8B%E5%BC%8F.html",
    "imgUrl": "./%E4%BA%BA%E8%87%89%E6%9B%BF%E6%8F%9B%E7%A8%8B%E5%BC%8F.jpg"
  },
  {
    "name": "人臉辨識替換程式",
    "url": "./%E4%BA%BA%E8%87%89%E8%BE%A8%E8%AD%98%E6%9B%BF%E6%8F%9B%E7%A8%8B%E5%BC%8F.html",
    "imgUrl": "./%E4%BA%BA%E8%87%89%E8%BE%A8%E8%AD%98%E6%9B%BF%E6%8F%9B%E7%A8%8B%E5%BC%8F.jpg"
  },
  {
    "name": "國語大家來找碴遊戲",
    "url": "./%E5%9C%8B%E8%AA%9E%E5%A4%A7%E5%AE%B6%E4%BE%86%E6%89%BE%E7%A2%B4%E9%81%8A%E6%88%B2.html",
    "imgUrl": "./%E5%9C%8B%E8%AA%9E%E5%A4%A7%E5%AE%B6%E4%BE%86%E6%89%BE%E7%A2%B4%E9%81%8A%E6%88%B2.jpg"
  },
  {
    "name": "國語生字魔法產生器",
    "url": "./%E5%9C%8B%E8%AA%9E%E7%94%9F%E5%AD%97%E9%AD%94%E6%B3%95%E7%94%A2%E7%94%9F%E5%99%A8.html",
    "imgUrl": "./%E5%9C%8B%E8%AA%9E%E7%94%9F%E5%AD%97%E9%AD%94%E6%B3%95%E7%94%A2%E7%94%9F%E5%99%A8.jpg"
  },
  {
    "name": "大家來找碴圖卡產生器(品質好)",
    "url": "./%E5%A4%A7%E5%AE%B6%E4%BE%86%E6%89%BE%E7%A2%B4%E5%9C%96%E5%8D%A1%E7%94%A2%E7%94%9F%E5%99%A8(%E5%93%81%E8%B3%AA%E5%A5%BD).html",
    "imgUrl": "./%E5%A4%A7%E5%AE%B6%E4%BE%86%E6%89%BE%E7%A2%B4%E5%9C%96%E5%8D%A1%E7%94%A2%E7%94%9F%E5%99%A8(%E5%93%81%E8%B3%AA%E5%A5%BD).jpg"
  },
  {
    "name": "客製化語詞與解釋 (5x5 賓果)",
    "url": "./%E5%AE%A2%E8%A3%BD%E5%8C%96%E8%AA%9E%E8%A9%9E%E8%88%87%E8%A7%A3%E9%87%8B%20(5x5%20%E8%B3%93%E6%9E%9C).html",
    "imgUrl": "./%E5%AE%A2%E8%A3%BD%E5%8C%96%E8%AA%9E%E8%A9%9E%E8%88%87%E8%A7%A3%E9%87%8B%20(5x5%20%E8%B3%93%E6%9E%9C).jpg"
  },
  {
    "name": "康軒三下國語聽語詞找卡片",
    "url": "./%E5%BA%B7%E8%BB%92%E4%B8%89%E4%B8%8B%E5%9C%8B%E8%AA%9E%E8%81%BD%E8%AA%9E%E8%A9%9E%E6%89%BE%E5%8D%A1%E7%89%87.html",
    "imgUrl": "./%E5%BA%B7%E8%BB%92%E4%B8%89%E4%B8%8B%E5%9C%8B%E8%AA%9E%E8%81%BD%E8%AA%9E%E8%A9%9E%E6%89%BE%E5%8D%A1%E7%89%87.jpg"
  },
  {
    "name": "康軒六下1-9課生字多寶遊戲",
    "url": "./%E5%BA%B7%E8%BB%92%E5%85%AD%E4%B8%8B1-9%E8%AA%B2%E7%94%9F%E5%AD%97%E5%A4%9A%E5%AF%B6%E9%81%8A%E6%88%B2.html",
    "imgUrl": "./%E5%BA%B7%E8%BB%92%E5%85%AD%E4%B8%8B1-9%E8%AA%B2%E7%94%9F%E5%AD%97%E5%A4%9A%E5%AF%B6%E9%81%8A%E6%88%B2.jpg"
  },
  {
    "name": "康軒六下國語聽語詞找卡片",
    "url": "./%E5%BA%B7%E8%BB%92%E5%85%AD%E4%B8%8B%E5%9C%8B%E8%AA%9E%E8%81%BD%E8%AA%9E%E8%A9%9E%E6%89%BE%E5%8D%A1%E7%89%87.html",
    "imgUrl": "./%E5%BA%B7%E8%BB%92%E5%85%AD%E4%B8%8B%E5%9C%8B%E8%AA%9E%E8%81%BD%E8%AA%9E%E8%A9%9E%E6%89%BE%E5%8D%A1%E7%89%87.jpg"
  },
  {
    "name": "康軒六下語詞打磚塊",
    "url": "./%E5%BA%B7%E8%BB%92%E5%85%AD%E4%B8%8B%E8%AA%9E%E8%A9%9E%E6%89%93%E7%A3%9A%E5%A1%8A.html",
    "imgUrl": "./%E5%BA%B7%E8%BB%92%E5%85%AD%E4%B8%8B%E8%AA%9E%E8%A9%9E%E6%89%93%E7%A3%9A%E5%A1%8A.jpg"
  },
  {
    "name": "康軒六下語詞洞察先機有選號機",
    "url": "./%E5%BA%B7%E8%BB%92%E5%85%AD%E4%B8%8B%E8%AA%9E%E8%A9%9E%E6%B4%9E%E5%AF%9F%E5%85%88%E6%A9%9F%E6%9C%89%E9%81%B8%E8%99%9F%E6%A9%9F.html",
    "imgUrl": "./%E5%BA%B7%E8%BB%92%E5%85%AD%E4%B8%8B%E8%AA%9E%E8%A9%9E%E6%B4%9E%E5%AF%9F%E5%85%88%E6%A9%9F%E6%9C%89%E9%81%B8%E8%99%9F%E6%A9%9F.jpg"
  },
  {
    "name": "康軒國語三下生字轉轉轉",
    "url": "./%E5%BA%B7%E8%BB%92%E5%9C%8B%E8%AA%9E%E4%B8%89%E4%B8%8B%E7%94%9F%E5%AD%97%E8%BD%89%E8%BD%89%E8%BD%89.html",
    "imgUrl": "./%E5%BA%B7%E8%BB%92%E5%9C%8B%E8%AA%9E%E4%B8%89%E4%B8%8B%E7%94%9F%E5%AD%97%E8%BD%89%E8%BD%89%E8%BD%89.jpg"
  },
  {
    "name": "康軒國語三下語詞賓果遊戲",
    "url": "./%E5%BA%B7%E8%BB%92%E5%9C%8B%E8%AA%9E%E4%B8%89%E4%B8%8B%E8%AA%9E%E8%A9%9E%E8%B3%93%E6%9E%9C%E9%81%8A%E6%88%B2.html",
    "imgUrl": "./%E5%BA%B7%E8%BB%92%E5%9C%8B%E8%AA%9E%E4%B8%89%E4%B8%8B%E8%AA%9E%E8%A9%9E%E8%B3%93%E6%9E%9C%E9%81%8A%E6%88%B2.jpg"
  },
  {
    "name": "康軒國語六下句子填空塔防遊戲",
    "url": "./%E5%BA%B7%E8%BB%92%E5%9C%8B%E8%AA%9E%E5%85%AD%E4%B8%8B%E5%8F%A5%E5%AD%90%E5%A1%AB%E7%A9%BA%E5%A1%94%E9%98%B2%E9%81%8A%E6%88%B2.html",
    "imgUrl": "./%E5%BA%B7%E8%BB%92%E5%9C%8B%E8%AA%9E%E5%85%AD%E4%B8%8B%E5%8F%A5%E5%AD%90%E5%A1%AB%E7%A9%BA%E5%A1%94%E9%98%B2%E9%81%8A%E6%88%B2.jpg"
  },
  {
    "name": "康軒國語六下打磚塊",
    "url": "./%E5%BA%B7%E8%BB%92%E5%9C%8B%E8%AA%9E%E5%85%AD%E4%B8%8B%E6%89%93%E7%A3%9A%E5%A1%8A.html",
    "imgUrl": "./%E5%BA%B7%E8%BB%92%E5%9C%8B%E8%AA%9E%E5%85%AD%E4%B8%8B%E6%89%93%E7%A3%9A%E5%A1%8A.jpg"
  },
  {
    "name": "康軒國語六下生字九宮格",
    "url": "./%E5%BA%B7%E8%BB%92%E5%9C%8B%E8%AA%9E%E5%85%AD%E4%B8%8B%E7%94%9F%E5%AD%97%E4%B9%9D%E5%AE%AE%E6%A0%BC.html",
    "imgUrl": "./%E5%BA%B7%E8%BB%92%E5%9C%8B%E8%AA%9E%E5%85%AD%E4%B8%8B%E7%94%9F%E5%AD%97%E4%B9%9D%E5%AE%AE%E6%A0%BC.jpg"
  },
  {
    "name": "康軒國語六下生字轉轉轉",
    "url": "./%E5%BA%B7%E8%BB%92%E5%9C%8B%E8%AA%9E%E5%85%AD%E4%B8%8B%E7%94%9F%E5%AD%97%E8%BD%89%E8%BD%89%E8%BD%89.html",
    "imgUrl": "./%E5%BA%B7%E8%BB%92%E5%9C%8B%E8%AA%9E%E5%85%AD%E4%B8%8B%E7%94%9F%E5%AD%97%E8%BD%89%E8%BD%89%E8%BD%89.jpg"
  },
  {
    "name": "康軒國語六下語詞填空防禦戰",
    "url": "./%E5%BA%B7%E8%BB%92%E5%9C%8B%E8%AA%9E%E5%85%AD%E4%B8%8B%E8%AA%9E%E8%A9%9E%E5%A1%AB%E7%A9%BA%E9%98%B2%E7%A6%A6%E6%88%B0.html",
    "imgUrl": "./%E5%BA%B7%E8%BB%92%E5%9C%8B%E8%AA%9E%E5%85%AD%E4%B8%8B%E8%AA%9E%E8%A9%9E%E5%A1%AB%E7%A9%BA%E9%98%B2%E7%A6%A6%E6%88%B0.jpg"
  },
  {
    "name": "康軒國語六下語詞小朋友下樓梯",
    "url": "./%E5%BA%B7%E8%BB%92%E5%9C%8B%E8%AA%9E%E5%85%AD%E4%B8%8B%E8%AA%9E%E8%A9%9E%E5%B0%8F%E6%9C%8B%E5%8F%8B%E4%B8%8B%E6%A8%93%E6%A2%AF.html",
    "imgUrl": "./%E5%BA%B7%E8%BB%92%E5%9C%8B%E8%AA%9E%E5%85%AD%E4%B8%8B%E8%AA%9E%E8%A9%9E%E5%B0%8F%E6%9C%8B%E5%8F%8B%E4%B8%8B%E6%A8%93%E6%A2%AF.jpg"
  },
  {
    "name": "康軒國語六下語詞格鬥遊戲",
    "url": "./%E5%BA%B7%E8%BB%92%E5%9C%8B%E8%AA%9E%E5%85%AD%E4%B8%8B%E8%AA%9E%E8%A9%9E%E6%A0%BC%E9%AC%A5%E9%81%8A%E6%88%B2.html",
    "imgUrl": "./%E5%BA%B7%E8%BB%92%E5%9C%8B%E8%AA%9E%E5%85%AD%E4%B8%8B%E8%AA%9E%E8%A9%9E%E6%A0%BC%E9%AC%A5%E9%81%8A%E6%88%B2.jpg"
  },
  {
    "name": "康軒國語六下語詞解釋塔防遊戲",
    "url": "./%E5%BA%B7%E8%BB%92%E5%9C%8B%E8%AA%9E%E5%85%AD%E4%B8%8B%E8%AA%9E%E8%A9%9E%E8%A7%A3%E9%87%8B%E5%A1%94%E9%98%B2%E9%81%8A%E6%88%B2.html",
    "imgUrl": "./%E5%BA%B7%E8%BB%92%E5%9C%8B%E8%AA%9E%E5%85%AD%E4%B8%8B%E8%AA%9E%E8%A9%9E%E8%A7%A3%E9%87%8B%E5%A1%94%E9%98%B2%E9%81%8A%E6%88%B2.jpg"
  },
  {
    "name": "康軒國語六下語詞解釋貪食蛇",
    "url": "./%E5%BA%B7%E8%BB%92%E5%9C%8B%E8%AA%9E%E5%85%AD%E4%B8%8B%E8%AA%9E%E8%A9%9E%E8%A7%A3%E9%87%8B%E8%B2%AA%E9%A3%9F%E8%9B%87.html",
    "imgUrl": "./%E5%BA%B7%E8%BB%92%E5%9C%8B%E8%AA%9E%E5%85%AD%E4%B8%8B%E8%AA%9E%E8%A9%9E%E8%A7%A3%E9%87%8B%E8%B2%AA%E9%A3%9F%E8%9B%87.jpg"
  },
  {
    "name": "康軒國語六下語詞賓果遊戲",
    "url": "./%E5%BA%B7%E8%BB%92%E5%9C%8B%E8%AA%9E%E5%85%AD%E4%B8%8B%E8%AA%9E%E8%A9%9E%E8%B3%93%E6%9E%9C%E9%81%8A%E6%88%B2.html",
    "imgUrl": "./%E5%BA%B7%E8%BB%92%E5%9C%8B%E8%AA%9E%E5%85%AD%E4%B8%8B%E8%AA%9E%E8%A9%9E%E8%B3%93%E6%9E%9C%E9%81%8A%E6%88%B2.jpg"
  },
  {
    "name": "數學三位數除以一位數值式除法引導",
    "url": "./%E6%95%B8%E5%AD%B8%E4%B8%89%E4%BD%8D%E6%95%B8%E9%99%A4%E4%BB%A5%E4%B8%80%E4%BD%8D%E6%95%B8%E5%80%BC%E5%BC%8F%E9%99%A4%E6%B3%95%E5%BC%95%E5%B0%8E.html",
    "imgUrl": "./%E6%95%B8%E5%AD%B8%E4%B8%89%E4%BD%8D%E6%95%B8%E9%99%A4%E4%BB%A5%E4%B8%80%E4%BD%8D%E6%95%B8%E5%80%BC%E5%BC%8F%E9%99%A4%E6%B3%95%E5%BC%95%E5%B0%8E.jpg"
  },
  {
    "name": "數學二位數除以一位數值式除法引導",
    "url": "./%E6%95%B8%E5%AD%B8%E4%BA%8C%E4%BD%8D%E6%95%B8%E9%99%A4%E4%BB%A5%E4%B8%80%E4%BD%8D%E6%95%B8%E5%80%BC%E5%BC%8F%E9%99%A4%E6%B3%95%E5%BC%95%E5%B0%8E.html",
    "imgUrl": "./%E6%95%B8%E5%AD%B8%E4%BA%8C%E4%BD%8D%E6%95%B8%E9%99%A4%E4%BB%A5%E4%B8%80%E4%BD%8D%E6%95%B8%E5%80%BC%E5%BC%8F%E9%99%A4%E6%B3%95%E5%BC%95%E5%B0%8E.jpg"
  },
  {
    "name": "數學互動式直式除法+學習單",
    "url": "./%E6%95%B8%E5%AD%B8%E4%BA%92%E5%8B%95%E5%BC%8F%E7%9B%B4%E5%BC%8F%E9%99%A4%E6%B3%95%2B%E5%AD%B8%E7%BF%92%E5%96%AE.html",
    "imgUrl": "./%E6%95%B8%E5%AD%B8%E4%BA%92%E5%8B%95%E5%BC%8F%E7%9B%B4%E5%BC%8F%E9%99%A4%E6%B3%95%2B%E5%AD%B8%E7%BF%92%E5%96%AE.jpg"
  },
  {
    "name": "數學互動式除法與學習單產生",
    "url": "./%E6%95%B8%E5%AD%B8%E4%BA%92%E5%8B%95%E5%BC%8F%E9%99%A4%E6%B3%95%E8%88%87%E5%AD%B8%E7%BF%92%E5%96%AE%E7%94%A2%E7%94%9F.html",
    "imgUrl": "./%E6%95%B8%E5%AD%B8%E4%BA%92%E5%8B%95%E5%BC%8F%E9%99%A4%E6%B3%95%E8%88%87%E5%AD%B8%E7%BF%92%E5%96%AE%E7%94%A2%E7%94%9F.jpg"
  },
  {
    "name": "數學分數計算格鬥遊戲",
    "url": "./%E6%95%B8%E5%AD%B8%E5%88%86%E6%95%B8%E8%A8%88%E7%AE%97%E6%A0%BC%E9%AC%A5%E9%81%8A%E6%88%B2.html",
    "imgUrl": "./%E6%95%B8%E5%AD%B8%E5%88%86%E6%95%B8%E8%A8%88%E7%AE%97%E6%A0%BC%E9%AC%A5%E9%81%8A%E6%88%B2.jpg"
  },
  {
    "name": "數學四則運算有括號塔防遊戲",
    "url": "./%E6%95%B8%E5%AD%B8%E5%9B%9B%E5%89%87%E9%81%8B%E7%AE%97%E6%9C%89%E6%8B%AC%E8%99%9F%E5%A1%94%E9%98%B2%E9%81%8A%E6%88%B2.html",
    "imgUrl": "./%E6%95%B8%E5%AD%B8%E5%9B%9B%E5%89%87%E9%81%8B%E7%AE%97%E6%9C%89%E6%8B%AC%E8%99%9F%E5%A1%94%E9%98%B2%E9%81%8A%E6%88%B2.jpg"
  },
  {
    "name": "數學基本計算塔防遊戲",
    "url": "./%E6%95%B8%E5%AD%B8%E5%9F%BA%E6%9C%AC%E8%A8%88%E7%AE%97%E5%A1%94%E9%98%B2%E9%81%8A%E6%88%B2.html",
    "imgUrl": "./%E6%95%B8%E5%AD%B8%E5%9F%BA%E6%9C%AC%E8%A8%88%E7%AE%97%E5%A1%94%E9%98%B2%E9%81%8A%E6%88%B2.jpg"
  },
  {
    "name": "數學基本計算街頭格鬥",
    "url": "./%E6%95%B8%E5%AD%B8%E5%9F%BA%E6%9C%AC%E8%A8%88%E7%AE%97%E8%A1%97%E9%A0%AD%E6%A0%BC%E9%AC%A5.html",
    "imgUrl": "./%E6%95%B8%E5%AD%B8%E5%9F%BA%E6%9C%AC%E8%A8%88%E7%AE%97%E8%A1%97%E9%A0%AD%E6%A0%BC%E9%AC%A5.jpg"
  },
  {
    "name": "數學基本計算街頭遊戲",
    "url": "./%E6%95%B8%E5%AD%B8%E5%9F%BA%E6%9C%AC%E8%A8%88%E7%AE%97%E8%A1%97%E9%A0%AD%E9%81%8A%E6%88%B2.html",
    "imgUrl": null
  },
  {
    "name": "數學基礎計算合作打怪遊戲",
    "url": "./%E6%95%B8%E5%AD%B8%E5%9F%BA%E7%A4%8E%E8%A8%88%E7%AE%97%E5%90%88%E4%BD%9C%E6%89%93%E6%80%AA%E9%81%8A%E6%88%B2.html",
    "imgUrl": "./%E6%95%B8%E5%AD%B8%E5%9F%BA%E7%A4%8E%E8%A8%88%E7%AE%97%E5%90%88%E4%BD%9C%E6%89%93%E6%80%AA%E9%81%8A%E6%88%B2.jpg"
  },
  {
    "name": "數學基礎計算合作打怪遊戲_三人四選一版",
    "url": "./%E6%95%B8%E5%AD%B8%E5%9F%BA%E7%A4%8E%E8%A8%88%E7%AE%97%E5%90%88%E4%BD%9C%E6%89%93%E6%80%AA%E9%81%8A%E6%88%B2_%E4%B8%89%E4%BA%BA%E5%9B%9B%E9%81%B8%E4%B8%80%E7%89%88.html",
    "imgUrl": "./%E6%95%B8%E5%AD%B8%E5%9F%BA%E7%A4%8E%E8%A8%88%E7%AE%97%E5%90%88%E4%BD%9C%E6%89%93%E6%80%AA%E9%81%8A%E6%88%B2_%E4%B8%89%E4%BA%BA%E5%9B%9B%E9%81%B8%E4%B8%80%E7%89%88.jpg"
  },
  {
    "name": "數學基礎計算合作打怪遊戲_四選一版",
    "url": "./%E6%95%B8%E5%AD%B8%E5%9F%BA%E7%A4%8E%E8%A8%88%E7%AE%97%E5%90%88%E4%BD%9C%E6%89%93%E6%80%AA%E9%81%8A%E6%88%B2_%E5%9B%9B%E9%81%B8%E4%B8%80%E7%89%88.html",
    "imgUrl": "./%E6%95%B8%E5%AD%B8%E5%9F%BA%E7%A4%8E%E8%A8%88%E7%AE%97%E5%90%88%E4%BD%9C%E6%89%93%E6%80%AA%E9%81%8A%E6%88%B2_%E5%9B%9B%E9%81%B8%E4%B8%80%E7%89%88.jpg"
  },
  {
    "name": "數學基礎計算打磚塊遊戲",
    "url": "./%E6%95%B8%E5%AD%B8%E5%9F%BA%E7%A4%8E%E8%A8%88%E7%AE%97%E6%89%93%E7%A3%9A%E5%A1%8A%E9%81%8A%E6%88%B2.html",
    "imgUrl": "./%E6%95%B8%E5%AD%B8%E5%9F%BA%E7%A4%8E%E8%A8%88%E7%AE%97%E6%89%93%E7%A3%9A%E5%A1%8A%E9%81%8A%E6%88%B2.jpg"
  },
  {
    "name": "數學基礎計算拔河遊戲",
    "url": "./%E6%95%B8%E5%AD%B8%E5%9F%BA%E7%A4%8E%E8%A8%88%E7%AE%97%E6%8B%94%E6%B2%B3%E9%81%8A%E6%88%B2.html",
    "imgUrl": "./%E6%95%B8%E5%AD%B8%E5%9F%BA%E7%A4%8E%E8%A8%88%E7%AE%97%E6%8B%94%E6%B2%B3%E9%81%8A%E6%88%B2.jpg"
  },
  {
    "name": "數學基礎計算拔河遊戲_四選一版",
    "url": "./%E6%95%B8%E5%AD%B8%E5%9F%BA%E7%A4%8E%E8%A8%88%E7%AE%97%E6%8B%94%E6%B2%B3%E9%81%8A%E6%88%B2_%E5%9B%9B%E9%81%B8%E4%B8%80%E7%89%88.html",
    "imgUrl": "./%E6%95%B8%E5%AD%B8%E5%9F%BA%E7%A4%8E%E8%A8%88%E7%AE%97%E6%8B%94%E6%B2%B3%E9%81%8A%E6%88%B2_%E5%9B%9B%E9%81%B8%E4%B8%80%E7%89%88.jpg"
  },
  {
    "name": "數學基礎計算拔河遊戲恐龍殭屍版",
    "url": "./%E6%95%B8%E5%AD%B8%E5%9F%BA%E7%A4%8E%E8%A8%88%E7%AE%97%E6%8B%94%E6%B2%B3%E9%81%8A%E6%88%B2%E6%81%90%E9%BE%8D%E6%AE%AD%E5%B1%8D%E7%89%88.html",
    "imgUrl": "./%E6%95%B8%E5%AD%B8%E5%9F%BA%E7%A4%8E%E8%A8%88%E7%AE%97%E6%8B%94%E6%B2%B3%E9%81%8A%E6%88%B2%E6%81%90%E9%BE%8D%E6%AE%AD%E5%B1%8D%E7%89%88.jpg"
  },
  {
    "name": "數學基礎計算拔河遊戲恐龍殭屍版_四選一版",
    "url": "./%E6%95%B8%E5%AD%B8%E5%9F%BA%E7%A4%8E%E8%A8%88%E7%AE%97%E6%8B%94%E6%B2%B3%E9%81%8A%E6%88%B2%E6%81%90%E9%BE%8D%E6%AE%AD%E5%B1%8D%E7%89%88_%E5%9B%9B%E9%81%B8%E4%B8%80%E7%89%88.html",
    "imgUrl": "./%E6%95%B8%E5%AD%B8%E5%9F%BA%E7%A4%8E%E8%A8%88%E7%AE%97%E6%8B%94%E6%B2%B3%E9%81%8A%E6%88%B2%E6%81%90%E9%BE%8D%E6%AE%AD%E5%B1%8D%E7%89%88_%E5%9B%9B%E9%81%B8%E4%B8%80%E7%89%88.jpg"
  },
  {
    "name": "數學基礎計算格鬥遊戲",
    "url": "./%E6%95%B8%E5%AD%B8%E5%9F%BA%E7%A4%8E%E8%A8%88%E7%AE%97%E6%A0%BC%E9%AC%A5%E9%81%8A%E6%88%B2.html",
    "imgUrl": "./%E6%95%B8%E5%AD%B8%E5%9F%BA%E7%A4%8E%E8%A8%88%E7%AE%97%E6%A0%BC%E9%AC%A5%E9%81%8A%E6%88%B2.jpg"
  },
  {
    "name": "數學基礎計算貪食蛇",
    "url": "./%E6%95%B8%E5%AD%B8%E5%9F%BA%E7%A4%8E%E8%A8%88%E7%AE%97%E8%B2%AA%E9%A3%9F%E8%9B%87.html",
    "imgUrl": "./%E6%95%B8%E5%AD%B8%E5%9F%BA%E7%A4%8E%E8%A8%88%E7%AE%97%E8%B2%AA%E9%A3%9F%E8%9B%87.jpg"
  },
  {
    "name": "數學基礎計算騎士防禦戰",
    "url": "./%E6%95%B8%E5%AD%B8%E5%9F%BA%E7%A4%8E%E8%A8%88%E7%AE%97%E9%A8%8E%E5%A3%AB%E9%98%B2%E7%A6%A6%E6%88%B0.html",
    "imgUrl": "./%E6%95%B8%E5%AD%B8%E5%9F%BA%E7%A4%8E%E8%A8%88%E7%AE%97%E9%A8%8E%E5%A3%AB%E9%98%B2%E7%A6%A6%E6%88%B0.jpg"
  },
  {
    "name": "數學泡泡射擊遊戲",
    "url": "./%E6%95%B8%E5%AD%B8%E6%B3%A1%E6%B3%A1%E5%B0%84%E6%93%8A%E9%81%8A%E6%88%B2.html",
    "imgUrl": null
  },
  {
    "name": "數學魔法對戰遊戲",
    "url": "./%E6%95%B8%E5%AD%B8%E9%AD%94%E6%B3%95%E5%B0%8D%E6%88%B0%E9%81%8A%E6%88%B2.html",
    "imgUrl": "./%E6%95%B8%E5%AD%B8%E9%AD%94%E6%B3%95%E5%B0%8D%E6%88%B0%E9%81%8A%E6%88%B2.jpg"
  },
  {
    "name": "數學魔法對戰遊戲_四選一版",
    "url": "./%E6%95%B8%E5%AD%B8%E9%AD%94%E6%B3%95%E5%B0%8D%E6%88%B0%E9%81%8A%E6%88%B2_%E5%9B%9B%E9%81%B8%E4%B8%80%E7%89%88.html",
    "imgUrl": "./%E6%95%B8%E5%AD%B8%E9%AD%94%E6%B3%95%E5%B0%8D%E6%88%B0%E9%81%8A%E6%88%B2_%E5%9B%9B%E9%81%B8%E4%B8%80%E7%89%88.jpg"
  },
  {
    "name": "新版語音報讀系統步驟一",
    "url": "./%E6%96%B0%E7%89%88%E8%AA%9E%E9%9F%B3%E5%A0%B1%E8%AE%80%E7%B3%BB%E7%B5%B1%E6%AD%A5%E9%A9%9F%E4%B8%80.html",
    "imgUrl": null
  },
  {
    "name": "新版語音報讀系統步驟二",
    "url": "./%E6%96%B0%E7%89%88%E8%AA%9E%E9%9F%B3%E5%A0%B1%E8%AE%80%E7%B3%BB%E7%B5%B1%E6%AD%A5%E9%A9%9F%E4%BA%8C.html",
    "imgUrl": null
  },
  {
    "name": "生字圖卡學習單產生器",
    "url": "./%E7%94%9F%E5%AD%97%E5%9C%96%E5%8D%A1%E5%AD%B8%E7%BF%92%E5%96%AE%E7%94%A2%E7%94%9F%E5%99%A8.html",
    "imgUrl": "./%E7%94%9F%E5%AD%97%E5%9C%96%E5%8D%A1%E5%AD%B8%E7%BF%92%E5%96%AE%E7%94%A2%E7%94%9F%E5%99%A8.png"
  },
  {
    "name": "生字圖卡產生器",
    "url": "./%E7%94%9F%E5%AD%97%E5%9C%96%E5%8D%A1%E7%94%A2%E7%94%9F%E5%99%A8.html",
    "imgUrl": "./%E7%94%9F%E5%AD%97%E5%9C%96%E5%8D%A1%E7%94%A2%E7%94%9F%E5%99%A8.png"
  },
  {
    "name": "翰林三下數學ch3分數的加減",
    "url": "./%E7%BF%B0%E6%9E%97%E4%B8%89%E4%B8%8B%E6%95%B8%E5%AD%B8ch3%E5%88%86%E6%95%B8%E7%9A%84%E5%8A%A0%E6%B8%9B.html",
    "imgUrl": "./%E7%BF%B0%E6%9E%97%E4%B8%89%E4%B8%8B%E6%95%B8%E5%AD%B8ch3%E5%88%86%E6%95%B8%E7%9A%84%E5%8A%A0%E6%B8%9B.jpg"
  },
  {
    "name": "翰林數學三年級上除法",
    "url": "./%E7%BF%B0%E6%9E%97%E6%95%B8%E5%AD%B8%E4%B8%89%E5%B9%B4%E7%B4%9A%E4%B8%8A%E9%99%A4%E6%B3%95.html",
    "imgUrl": "./%E7%BF%B0%E6%9E%97%E6%95%B8%E5%AD%B8%E4%B8%89%E5%B9%B4%E7%B4%9A%E4%B8%8A%E9%99%A4%E6%B3%95.jpg"
  },
  {
    "name": "考試提醒儀錶板",
    "url": "./%E8%80%83%E8%A9%A6%E6%8F%90%E9%86%92%E5%84%80%E9%8C%B6%E6%9D%BF.html",
    "imgUrl": "./%E8%80%83%E8%A9%A6%E6%8F%90%E9%86%92%E5%84%80%E9%8C%B6%E6%9D%BF.jpg"
  },
  {
    "name": "聽聲音找語詞",
    "url": "./%E8%81%BD%E8%81%B2%E9%9F%B3%E6%89%BE%E8%AA%9E%E8%A9%9E.html",
    "imgUrl": "./%E8%81%BD%E8%81%B2%E9%9F%B3%E6%89%BE%E8%AA%9E%E8%A9%9E.jpg"
  },
  {
    "name": "語音輸入輔導紀錄資源班版",
    "url": "./%E8%AA%9E%E9%9F%B3%E8%BC%B8%E5%85%A5%E8%BC%94%E5%B0%8E%E7%B4%80%E9%8C%84%E8%B3%87%E6%BA%90%E7%8F%AD%E7%89%88.html",
    "imgUrl": "./%E8%AA%9E%E9%9F%B3%E8%BC%B8%E5%85%A5%E8%BC%94%E5%B0%8E%E7%B4%80%E9%8C%84%E8%B3%87%E6%BA%90%E7%8F%AD%E7%89%88.jpg"
  },
  {
    "name": "輔導紀錄公測版",
    "url": "./%E8%BC%94%E5%B0%8E%E7%B4%80%E9%8C%84%E5%85%AC%E6%B8%AC%E7%89%88.html",
    "imgUrl": null
  }
];
