import { readdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = fileURLToPath(new URL('../', import.meta.url));
const entries = await readdir(root, { withFileTypes: true });
const files = new Set(entries.filter(entry => entry.isFile()).map(entry => entry.name));
const catalog = [...files]
  .filter(name => name.endsWith('.html') && name !== 'index.html' && !name.startsWith('.'))
  .sort()
  .map(file => {
    const name = file.slice(0, -5);
    const preview = ['.jpg', '.png', '.jpeg', '.webp'].map(ext => name + ext).find(image => files.has(image));
    return {
      name,
      url: './' + encodeURIComponent(file),
      imgUrl: preview ? './' + encodeURIComponent(preview) : null,
    };
  });

await writeFile(path.join(root, 'games.js'),
  '// Generated by scripts/generate-catalog.mjs. Do not edit manually.\n' +
  'window.GAME_CATALOG = ' + JSON.stringify(catalog, null, 2) + ';\n', 'utf8');
console.log(`Generated catalog for ${catalog.length} pages.`);
